import "~/styles/globals.css";
import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { SessionProvider } from "next-auth/react"; // Import SessionProvider
import { TRPCReactProvider } from "~/trpc/react";
import Sidebar from "./_components/sidebar";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body className="h-screen overflow-hidden">
        {/* Wrap your entire app with SessionProvider */}
        <TRPCReactProvider>
          {/* Wrapper div for layout */}
          <div className="flex h-screen">
            {/* Main content should take the rest of the space */}
            <main className="flex-1 overflow-y-auto p-6">{children}</main>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
